version: '3.3'
services:
 
  redis:
    image: redis
    ports:
      - '6379:6379' 
    container_name: redis  
    volumes:
      - ~/volumes/tredis:/data
    networks:
      - rnet  
      
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=redis
    ports:
    - 8081:8081
    networks:
      - rnet
     
  tiny:
    image: tiny
    build: ./tiny
    container_name: tiny
    restart: always
    links:
        - redis
    depends_on:
        - redis
    ports:
        - '8004:8004'   
    networks:
        - rnet
networks:
    rnet:
      driver: bridge
